### ISSUE TITLE
lone checkbox

### ISSUE THREAD

**Issue by WillieBHines** [wallter/codeigniter_bootstrap_form_builder#11]
Is there a way to do suppress one of the labels for the checkbox group? Right now, if only one checkbox is included, it has two labels: one for the group, and one for the box itself.

**Comment by Shakespeare2000** [comment]
I've created a PR (#12) which might help.

Create a checkbox without a 'main' label (in the label column), with only a label right of the checkbox with:

```
array(
    'id' => 'checkbox_group',
    'label' => 'none',
    'type' => 'checkbox',
    'options' => array(
        array(
            'id' => 'checkbox',
            'value' => 'agree',
            'label' => 'I agree'
        )
    )
)
```

Or create a checkbox with only a 'main' label with:

```
array(
    'id' => 'checkbox_group',
    'label' => 'I agree',
    'type' => 'checkbox',
    'options' => array(
        array(
            'id' => 'checkbox',
            'value' => 'agree',
            'label' => ''
        )
    )
)
```
