### ISSUE TITLE
how to create <option value="1" selected="selected">Published</option> 

### ISSUE THREAD

**Issue by ghost** [wallter/codeigniter_bootstrap_form_builder#16]
i cant make  <option value="1" selected="selected">Published</option> 
			array(/* DROP DOWN */
						'id' => 'published',
						'type' => 'dropdown',
						'options' => array(
								'1' => 'Published',
								'2' => 'Disabled'
						)

**Comment by wallter** [comment]
Could you provide the full code you're using?

**Comment by burhanahmed92** [comment]
any solution yet ! how to create placeholder in dropdown list?

**Comment by sree541** [comment]
@burhanahmed92  and  @alikodor. This may work for you. Please check it out.
>array(/* DROP DOWN */
		'id' => 'published',
		'type' => 'dropdown',
		'options' => array(
			'1' => 'Published',
			'2' => 'Disabled'
		),
		**'value' => '2'**
	),
Give 'value' of the option to be selecetd.
